// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: true,
  firebaseConfig: {
    apiKey: "AIzaSyBCf2G1Ojncn0Rqq1S8G6yl_5z8uD7Cn2M",
    authDomain: "multiplos-14183.firebaseapp.com",
    projectId: "multiplos-14183",
    storageBucket: "multiplos-14183.appspot.com",
    messagingSenderId: "322038037071",
    appId: "1:322038037071:web:1e341acf396021da4fc83a"
  },
};
